print ('Welcome to the Elite 101 Chatbot!')
print ('What is your name?')
name if input()
print ('Hello' + name + 'Nice to meet you! How old are you?')
age = input()
print ('Wow!' + age + 'you must be very whismical and mature!')
print('Please choose from the following options:')
print('1. Option 1')
print('2. Option 2')
print('3. Option 3')
print('4. Option 4')
print('4. Exit the COnversation')
choice = input()
if choice == '4':
  print('Goodbye!' + name + 'Hope u have a great day')
